### ISSUE TITLE
No ability to set system properties for the benchmark

### ISSUE THREAD

**Issue by KarolS** [artyushov/idea-jmh-plugin#16]
The run configuration dialog doesn't allow for specifying any options for the JVM including, but not limited to, system properties. Having to do `System.setProperty(...)` in the constructor doesn't look clean.

**Comment by IceMan81** [comment]
I have the same issue.

**Comment by artyushov** [comment]
If the issue is still relevant, could you tell me if `-jvmArgs` program parameter solves the problem?

**Comment by KarolS** [comment]
It works, unless I use @Fork(0). I think it's fine then.

**Comment by knittl** [comment]
This is very annoying when the classpath is too long ("CreateProcess error=206"). There should be an option in JMH starting with 1.20 (`jmh.separateClasspathJAR`), but setting this option in `@Fork` or in the Benchmark class' constructor (via `System.setProperty`) does not seem to help :(

Is there a workaround to have the JMH plugin start JMH in such a way so that forks can start even with overly long classpaths?

**Comment by stokito** [comment]
Now it works and you'll see VM Options in run configuration but you have to always add `-D` for them
