### ISSUE TITLE
Plugin doesn't work on Windows with IntelliJ 2016.1.1?

### ISSUE THREAD

**Issue by Jire** [artyushov/idea-jmh-plugin#19]
When running it seems like it tries to access an invalid path for its lock.

```
ERROR: org.openjdk.jmh.runner.RunnerException: ERROR: Exception while trying to acquire the JMH lock (C:\Windows\/jmh.lock): Access is denied, exiting. Use -Djmh.ignoreLock=true to forcefully continue.
    at org.openjdk.jmh.runner.Runner.run(Runner.java:213)
    at org.openjdk.jmh.Main.main(Main.java:71)
```

**Comment by artyushov** [comment]
Hi.

Can you run your benchmarks without plugin?

**Comment by Jire** [comment]
Yes, completely.

**Comment by geld0r** [comment]
I also see this error. I am running the same version under Windows.

I can run benchmarks via gradle successfully (via [jmh-gradle-plugin](https://github.com/melix/jmh-gradle-plugin) - is it possible that they conflict?

**Comment by artyushov** [comment]
There is nothing really I can do about it, it's not a plugin issue. The exception is thrown by the JMH runner itself which tries to acquire a lock `jmh.lock` which is located inside `java.io.tmpdir`. Try changing this property to point to a directory where your process has required permissions.

**Comment by kiril-dayradzhiev** [comment]
Hi all,
I met the same issue.
@artyushov you proposed to change **java.io.tmpdir**, but how? By using **jvmArgs**?

Best Regards,
Kiril

**Comment by Jire** [comment]
@artyushov We cannot do this trivially through the plugin since there is nowhere to state arguments.

**Comment by KarolS** [comment]
@Jire You can add the TMP environment variable in the plugin configuration and point it to any writeable directory.

**Comment by JavaOPs** [comment]
One more solution: run idea64.exe as Administrator

**Comment by kiril-dayradzhiev** [comment]
Here is the only solution that works for me ->http://stackoverflow.com/questions/37720692/exception-while-trying-to-acquire-a-jmh-lock

**Comment by KarolS** [comment]
@kiril-dayradzhiev ` java.io.tmpdir` is not an environment variable, it's a Java system property, which on Windows is by default set to the `TMP` environment variable. The plugin doesn't let you set Java properties, but lets you set environment variables.

**Comment by viliam-durina** [comment]
`java.io.tmpdir` on windows is normally `c:\Users\userName\AppData\Local\Temp`, so the JMH does not use this one. If it did, this directory is writable.

**Comment by mjeffrey** [comment]
In the "Run/Debug Configuration" dialog  set the "Environment variables:" field to a writable directory
e.g. 

> TEMP=c:\tmp

![image](https://user-images.githubusercontent.com/1449080/69612375-d8800f80-102f-11ea-9bd0-78fc3f83873c.png)

**Comment by knittl** [comment]
Or, alternatively, check the checkbox to include system defined environment variables in the environment variables dialog (opened via the "page icon" on the right side of the text box).

Not sure if this could have a negative impact on the benchmarks though …

**Comment by joserobjr** [comment]
> One more solution: run idea64.exe as Administrator

And let a broken plugin make a mess in `C:\Windows`? No way.

**Comment by stokito** [comment]
When JMH starts [it checks that there no any other JMH process running on the machine](https://github.com/openjdk/jmh/blob/095c5d45887e71bbafbc51400faa425f56997367/jmh-core/src/main/java/org/openjdk/jmh/runner/Runner.java#L183).
To check it tries to create the `jmh.lock` file in systems temporary folder. Another process may check if the file is exists and wait while it will be removed. Instead of a lock file programs may use socket or even see processes list `ps | prep` to determine that there is no any running process in the system. Unfortunately JVM doesn't have a built-in single instance checker API and IMHO it would be really nice to have.

The standard Java API has a `File.createTempFile(prefix, suffix)` but it always creates a file with random name so other processes can't find the same file. Instead JMH gets the system property `java.io.tmpdir` and creates the `jmh.lock` file inside.

In Linux/UNIX the `java.io.tmpdir` is always `/tmp/` folder. Note that all users have an access to folder.
On Windows when you call `System.getProperty("java.io.tmpdir")` Java calls the Win32 API's function `GetTempPath`.
According to [the MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364992%28v=vs.85%29.aspx):

> The `GetTempPath` function checks for the existence of environment
> variables in the following order and uses the first path found:
> 
>  1. The path specified by the `TMP` environment variable.
>  2. The path specified by the `TEMP` environment variable. [The historical reasons on why `TMP` and `TEMP` coexist](https://devblogs.microsoft.com/oldnewthing/20150417-00/?p=44213).
>  3. The path specified by the `USERPROFILE` environment variable.
>  4. The Windows directory `C:\WINDOWS\`.

So what really happens is that when we are starting JMH benchmark from IntelliJ the environment variables are really empty and the `java.io.tmpdir` returns `C:\WINDOWS\`. But access to the folder is denied. System variables looks like:

    "java.io.tmpdir" -> "C:\WINDOWS\"
    "java.library.path" -> "C:\Program Files\Zulu\zulu-8\bin;
        C:\WINDOWS\Sun\Java\bin;
        C:\WINDOWS\system32;
        C:\WINDOWS;."

But if in run configuration check `Include system environment variables` then will be copied the `TMP`, `TEMP`, `USERPROFILE` variables which are probably already configured system wide. So the resulted  `java.io.tmpdir` will return `C:\Users\Admin\AppData\Local\Temp\` i.e. user specific temp folder. Interesting, that other users in system still can run JMH simultaneously.

So the workaround was committed in 7b98e73 to create by default JMH configuration with already checked `Include system environment variables`. But actually this still not guaranties that `TMP`, `TEMP`, `USERPROFILE` variables are set in system.
Also this may have some side effects: when you inherit system envs then `java.library.path` system variable is also affected:

    "java.io.tmpdir" -> "C:\Users\Admin\AppData\Local\Temp\"
    "java.library.path" -> "C:\Program Files\Zulu\zulu-8\bin;
        C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;
        C:\WINDOWS;
        C:\WINDOWS\system32;

I.e. the property is affected by `PATH` env. The `java.library.path` is used by JNI to find DLL with native code.
So technically speaking 




The similar issues exists for JMH gradle plugin:
* https://github.com/melix/jmh-gradle-plugin/issues/104
* https://github.com/melix/jmh-gradle-plugin/issues/105

I think it would be great to fix it in JMH itself in this place:


But currently I have no idea how to fix it properly.

**Comment by knittl** [comment]
@stokito I have created a follow-up MR to limit the impact of inheriting environment variables to Windows systems only: #40 

See related, original MR https://github.com/knittl/idea-jmh-plugin/pull/1
