### ISSUE TITLE
Support Kotlin class

### ISSUE THREAD

**Issue by debop** [artyushov/idea-jmh-plugin#21]
current jmh plugin does not run Kotlin Benchmark class 
Could you support Kotlin class?

**Comment by stokito** [comment]
To support of Kotlin and other JVM languages we should migrate to new Universal Abstract Syntax Tree (UAST).
Since this migration is a major change and may bring a lot of new bugs then it will be better to do this in a separate release v1.2
I did some POC and looks like we do can implement this but I'm afraid we'll have some performance regression of the plugin itself: detection of such benchmark methods will produce conversion of `PsiElement` to `UElement`.
Still most users wont see a difference, just their laptop battery will discharged faster.
I pushed the code for v1.2 into a separate branch https://github.com/artyushov/idea-jmh-plugin/tree/v1.2

Any help appreciated.

**Comment by stokito** [comment]
ok, so I migrated to UAST but not everywhere. So Kotlin supported not completely e.g. inspections not works and even has bugs.
But, you can run Kotlin benchmarks so at least basic support works.
I'll close the ticket because I don't have any plans to do any work in this direction.
But any PRs will be appreciated.
