### ISSUE TITLE
Android Studio: Unable to find plugin in repository

### ISSUE THREAD

**Issue by IgorGanapolsky** [artyushov/idea-jmh-plugin#25]
Hi,
your README states:
> search for JMH in plugin repositories

However, in Android Studio I am unable to find this plugin in the repositories:

![screen shot 2017-03-06 at 10 20 00 am](https://cloud.githubusercontent.com/assets/201209/23616062/7d63c298-0256-11e7-919c-0d778d468a71.png)

**Comment by stokito** [comment]
In ddd64f609207c2a498ee21723d76aff0e2903dfe I added  `<depends>com.intellij.modules.java</depends>` to `plugin.xml` and this should fix the issue. After release we need to recheck it.

**Comment by stokito** [comment]
I just checked and now the plugin is available in Android Studio. BUT please note that JMH supports only HotSpot JDK and its benchmarks may be not useful for Andoid apps. Here is a good article on the subject https://habr.com/ru/company/oleg-bunin/blog/420143/

**Comment by stokito** [comment]
FYI: Starting from IntelliJ 2020.3 all plugin must be compiled with JDK 11.
So in v1.2 I recompiled the plugin and I accidentally broke the Android Studio support:

    Caused by: java.lang.UnsupportedClassVersionError: ru/artyushov/jmhPlugin/configuration/JmhConfigurationType has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

This happens because Android Studio not yet fully migrated to JDK 11 but the latest beta release 4.2. Canary 15 already switched to JBR 11. So just try to download the latest available Android Studio
