### ISSUE TITLE
Add screenshot to the plugins description

### ISSUE THREAD

**Issue by stokito** [artyushov/idea-jmh-plugin#39]

**Comment by rybak** [comment]
Hello @stokito.

Could you please tell me which software did you use to produce [the gif](/artyushov/idea-jmh-plugin/blob/develop/demo.gif)? It is surprising that such a small gif, just 792 kilobytes, gives such clear visuals for a long duration.

![](https://raw.githubusercontent.com/artyushov/idea-jmh-plugin/develop/demo.gif)

**Comment by stokito** [comment]
Sorry, don't remember exactly. I remember that once I used Peek but there is also many of other tools:
https://askubuntu.com/questions/107726/how-to-create-animated-gif-images-of-a-screencast
I remember that once I used some command line tool to record a screencast.

Another time I used OBS Studio and then converted video to a gif with ffmpeg. Here some samples https://superuser.com/questions/556029/how-do-i-convert-a-video-to-gif-using-ffmpeg-with-reasonable-quality

I would recommend to use the OBS because this is the most advanced tool for screencasts and streams and your invested time will be useful. The ffmeg command line to convert to a GIF can be googled quickly.

**Comment by rybak** [comment]
> Another time I used OBS Studio and then converted video to a gif with ffmpeg. Here some samples https://superuser.com/questions/556029/how-do-i-convert-a-video-to-gif-using-ffmpeg-with-reasonable-quality

This worked great for me, thank you for the pointers!

### Recording

I've used OBS Studio to record. I had to use cropped Screen Capture, because context menus don't show up in window capture. The important bit is using "Lossless Quality, Tremendously Large File Size" in "File > Settings > Output > Recording > Recording Quality".

Video settings: 1024x768 for canvas and output resolution; Bilinear filter; 10 FPS.

I've recorded 33 seconds. This resulted in a 91 megabytes `.avi` file.

### Editing
I've edited the raw footage (in my case, just cutting out parts to make it shorter) using [Kdenlive](https://kdenlive.org/). Again, using lossless settings is important. In dialog "Project > Render...", select "Lossless/HQ > FFV1 (ffv1+flac)".

### Converting to gif
I've adapted the command from the superuser.com answer:

```
ffmpeg -i kdenlive-render.mkv \
    -vf 'split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse' \
    ffmpeg-superuser-palette.gif
```

> * [palettegen][7] and [paletteuse][8] filters will generate and use a custom palette generated from your input. These filters have many options, so refer to the links for a list of all available options and values. Also see the **Advanced options** section below.
> * [split][9] filter will allow everything to be done in one command and avoids having to create a temporary PNG file of the palette.

And the result is a gif file of just 347 kilobytes! Thanks again.

  [7]: https://ffmpeg.org/ffmpeg-filters.html#palettegen
  [8]: https://ffmpeg.org/ffmpeg-filters.html#paletteuse
  [9]: https://ffmpeg.org/ffmpeg-filters.html#split

**Comment by stokito** [comment]
Hope one day it will be much simpler. I remember there was a websites to make a screencast. You just share your screen like in Zoom.
