### ISSUE TITLE
Empty run configuration in IntelliJ IDEA 2024.1 Beta

### ISSUE THREAD

**Issue by delanym** [artyushov/idea-jmh-plugin#50]
No run configuration is generated for this version of IntelliJ. Plugin v1.4.0.

**Comment by stokito** [comment]
Thank you for the reporting. Will check on weekend

**Comment by paragverma-v1** [comment]
Any update?

**Comment by stokito** [comment]
Unfortunately I can't figure out why this happens and how to fix it properly. But I copied some code from another plugin and it works but not as before: it will show a green triangle Run and Debug instead of yellow triangle Run.
It become so complicated with so many changes so that if something will be broke then only IntelliJ devs can fix that (but they won't)

**Comment by stokito** [comment]
In a week you should receive and update of the plugin, so please try and report if any issues

**Comment by stokito** [comment]
OMG the plugin was already approved
https://plugins.jetbrains.com/plugin/7529-jmh-java-microbenchmark-harness/versions/stable/530903

Happy international Labor Day!
